{% set name = "pytest-asyncio-cooperative" %}
{% set version = "0.30.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e657d796aed1956b6e2b55740d260da12f8e2ec0f6500ddd129f81eb4d4ec7e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.0
  run:
    - python >=3.7
    - pytest

test:
  imports:
    - pytest_asyncio_cooperative
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytest-asyncio-cooperative/
  summary: Run all your asynchronous tests cooperatively.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
