{% set name = "pytest-asyncio-cooperative" %}
{% set version = "0.31.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 05355af6f2757b8d7a7eee5333387803d5834170402a2128d5675d9b414ab252

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.0
  run:
    - python >=3.7
    - pytest

test:
  imports:
    - pytest_asyncio_cooperative
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytest-asyncio-cooperative/
  summary: Run all your asynchronous tests cooperatively.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
